server:
  port: 8081

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
